language: python

python: 3.5
env:
  - TOXENV=d19-py27
  - TOXENV=d110-py27

  - TOXENV=d19-py33
  - TOXENV=d110-py33

  - TOXENV=d19-py34
  - TOXENV=d110-py34

  - TOXENV=d19-py35
  - TOXENV=d110-py35

install:
  - pip install -U tox

script:
  - tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
