# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('integer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DemoModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('integer', models.IntegerField(default=0)),
            ],
        ),
    ]
